image: golang:latest
variables:
  SECURE_FILES_DOWNLOAD_PATH: .
  PRIVATE_KEY_NAME: id_rsa.toolforge
  SSH_USER: nokibsarkar

stages:
  - deploy
.deploy: &deploy
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "fake-nginx"'
  script:
    - mkdir -p ~/.ssh
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - mv $SECURE_FILES_DOWNLOAD_PATH/$PRIVATE_KEY_NAME ~/.ssh
    - chmod 600 ~/.ssh/$PRIVATE_KEY_NAME
    - wc -cwl ~/.ssh/$PRIVATE_KEY_NAME
    - echo "Username $SSH_USER"
    - echo "Host $SSH_HOST"
    - echo "Environment $env"
    - |
      ssh -i "~/.ssh/$PRIVATE_KEY_NAME" "$SSH_USER@$SSH_HOST" 'bash -s' <<EOF
      become "$TOOLNAME"
      toolforge build start -L --image-name campwiz-backend-fake-nginx https://gitlab.wikimedia.org/nokibsarkar/campwiz-backend.git --ref fake-nginx
      toolforge webservice buildservice restart --mount all --buildservice-image tool-campwiz-backend/campwiz-backend-fake-nginx:latest
      exit
      exit
      EOF
deploy-to-dev:
  stage: deploy
  environment: development
  variables:
    TOOLNAME: campwiz-backend-dev
  <<: *deploy
deploy-to-beta:
  stage: deploy
  environment: beta
  variables:
    TOOLNAME: campwiz-backend-beta
  <<: *deploy
deploy-to-prod:
  stage: deploy
  environment: production
  variables:
    TOOLNAME: campwiz-backend
  <<: *deploy
