// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"nokib/campwiz/models"
)

func newTask(db *gorm.DB, opts ...gen.DOOption) task {
	_task := task{}

	_task.taskDo.UseDB(db, opts...)
	_task.taskDo.UseModel(&models.Task{})

	tableName := _task.taskDo.TableName()
	_task.ALL = field.NewAsterisk(tableName)
	_task.TaskID = field.NewString(tableName, "task_id")
	_task.Type = field.NewString(tableName, "type")
	_task.Status = field.NewString(tableName, "status")
	_task.AssociatedRoundID = field.NewString(tableName, "associated_round_id")
	_task.AssociatedCampaignID = field.NewString(tableName, "associated_campaign_id")
	_task.AssociatedUserID = field.NewString(tableName, "associated_user_id")
	_task.Data = field.NewField(tableName, "data")
	_task.CreatedAt = field.NewTime(tableName, "created_at")
	_task.UpdatedAt = field.NewTime(tableName, "updated_at")
	_task.SuccessCount = field.NewInt(tableName, "success_count")
	_task.FailedCount = field.NewInt(tableName, "failed_count")
	_task.FailedIds = field.NewField(tableName, "failed_ids")
	_task.RemainingCount = field.NewInt(tableName, "remaining_count")
	_task.CreatedByID = field.NewString(tableName, "created_by_id")
	_task.TaskData = taskHasManyTaskData{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("TaskData", "models.TaskData"),
		Task: struct {
			field.RelationField
			Submittor struct {
				field.RelationField
				LeadingProject struct {
					field.RelationField
				}
			}
			TaskData struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("TaskData.Task", "models.Task"),
			Submittor: struct {
				field.RelationField
				LeadingProject struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("TaskData.Task.Submittor", "models.User"),
				LeadingProject: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("TaskData.Task.Submittor.LeadingProject", "models.Project"),
				},
			},
			TaskData: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("TaskData.Task.TaskData", "models.TaskData"),
			},
		},
	}

	_task.Submittor = taskBelongsToSubmittor{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Submittor", "models.User"),
	}

	_task.fillFieldMap()

	return _task
}

type task struct {
	taskDo

	ALL                  field.Asterisk
	TaskID               field.String
	Type                 field.String
	Status               field.String
	AssociatedRoundID    field.String
	AssociatedCampaignID field.String
	AssociatedUserID     field.String
	Data                 field.Field
	CreatedAt            field.Time
	UpdatedAt            field.Time
	SuccessCount         field.Int
	FailedCount          field.Int
	FailedIds            field.Field
	RemainingCount       field.Int
	CreatedByID          field.String
	TaskData             taskHasManyTaskData

	Submittor taskBelongsToSubmittor

	fieldMap map[string]field.Expr
}

func (t task) Table(newTableName string) *task {
	t.taskDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t task) As(alias string) *task {
	t.taskDo.DO = *(t.taskDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *task) updateTableName(table string) *task {
	t.ALL = field.NewAsterisk(table)
	t.TaskID = field.NewString(table, "task_id")
	t.Type = field.NewString(table, "type")
	t.Status = field.NewString(table, "status")
	t.AssociatedRoundID = field.NewString(table, "associated_round_id")
	t.AssociatedCampaignID = field.NewString(table, "associated_campaign_id")
	t.AssociatedUserID = field.NewString(table, "associated_user_id")
	t.Data = field.NewField(table, "data")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.SuccessCount = field.NewInt(table, "success_count")
	t.FailedCount = field.NewInt(table, "failed_count")
	t.FailedIds = field.NewField(table, "failed_ids")
	t.RemainingCount = field.NewInt(table, "remaining_count")
	t.CreatedByID = field.NewString(table, "created_by_id")

	t.fillFieldMap()

	return t
}

func (t *task) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *task) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 16)
	t.fieldMap["task_id"] = t.TaskID
	t.fieldMap["type"] = t.Type
	t.fieldMap["status"] = t.Status
	t.fieldMap["associated_round_id"] = t.AssociatedRoundID
	t.fieldMap["associated_campaign_id"] = t.AssociatedCampaignID
	t.fieldMap["associated_user_id"] = t.AssociatedUserID
	t.fieldMap["data"] = t.Data
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["success_count"] = t.SuccessCount
	t.fieldMap["failed_count"] = t.FailedCount
	t.fieldMap["failed_ids"] = t.FailedIds
	t.fieldMap["remaining_count"] = t.RemainingCount
	t.fieldMap["created_by_id"] = t.CreatedByID

}

func (t task) clone(db *gorm.DB) task {
	t.taskDo.ReplaceConnPool(db.Statement.ConnPool)
	t.TaskData.db = db.Session(&gorm.Session{Initialized: true})
	t.TaskData.db.Statement.ConnPool = db.Statement.ConnPool
	t.Submittor.db = db.Session(&gorm.Session{Initialized: true})
	t.Submittor.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t task) replaceDB(db *gorm.DB) task {
	t.taskDo.ReplaceDB(db)
	t.TaskData.db = db.Session(&gorm.Session{})
	t.Submittor.db = db.Session(&gorm.Session{})
	return t
}

type taskHasManyTaskData struct {
	db *gorm.DB

	field.RelationField

	Task struct {
		field.RelationField
		Submittor struct {
			field.RelationField
			LeadingProject struct {
				field.RelationField
			}
		}
		TaskData struct {
			field.RelationField
		}
	}
}

func (a taskHasManyTaskData) Where(conds ...field.Expr) *taskHasManyTaskData {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a taskHasManyTaskData) WithContext(ctx context.Context) *taskHasManyTaskData {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a taskHasManyTaskData) Session(session *gorm.Session) *taskHasManyTaskData {
	a.db = a.db.Session(session)
	return &a
}

func (a taskHasManyTaskData) Model(m *models.Task) *taskHasManyTaskDataTx {
	return &taskHasManyTaskDataTx{a.db.Model(m).Association(a.Name())}
}

func (a taskHasManyTaskData) Unscoped() *taskHasManyTaskData {
	a.db = a.db.Unscoped()
	return &a
}

type taskHasManyTaskDataTx struct{ tx *gorm.Association }

func (a taskHasManyTaskDataTx) Find() (result []*models.TaskData, err error) {
	return result, a.tx.Find(&result)
}

func (a taskHasManyTaskDataTx) Append(values ...*models.TaskData) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a taskHasManyTaskDataTx) Replace(values ...*models.TaskData) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a taskHasManyTaskDataTx) Delete(values ...*models.TaskData) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a taskHasManyTaskDataTx) Clear() error {
	return a.tx.Clear()
}

func (a taskHasManyTaskDataTx) Count() int64 {
	return a.tx.Count()
}

func (a taskHasManyTaskDataTx) Unscoped() *taskHasManyTaskDataTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type taskBelongsToSubmittor struct {
	db *gorm.DB

	field.RelationField
}

func (a taskBelongsToSubmittor) Where(conds ...field.Expr) *taskBelongsToSubmittor {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a taskBelongsToSubmittor) WithContext(ctx context.Context) *taskBelongsToSubmittor {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a taskBelongsToSubmittor) Session(session *gorm.Session) *taskBelongsToSubmittor {
	a.db = a.db.Session(session)
	return &a
}

func (a taskBelongsToSubmittor) Model(m *models.Task) *taskBelongsToSubmittorTx {
	return &taskBelongsToSubmittorTx{a.db.Model(m).Association(a.Name())}
}

func (a taskBelongsToSubmittor) Unscoped() *taskBelongsToSubmittor {
	a.db = a.db.Unscoped()
	return &a
}

type taskBelongsToSubmittorTx struct{ tx *gorm.Association }

func (a taskBelongsToSubmittorTx) Find() (result *models.User, err error) {
	return result, a.tx.Find(&result)
}

func (a taskBelongsToSubmittorTx) Append(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a taskBelongsToSubmittorTx) Replace(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a taskBelongsToSubmittorTx) Delete(values ...*models.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a taskBelongsToSubmittorTx) Clear() error {
	return a.tx.Clear()
}

func (a taskBelongsToSubmittorTx) Count() int64 {
	return a.tx.Count()
}

func (a taskBelongsToSubmittorTx) Unscoped() *taskBelongsToSubmittorTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type taskDo struct{ gen.DO }

type ITaskDo interface {
	gen.SubQuery
	Debug() ITaskDo
	WithContext(ctx context.Context) ITaskDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITaskDo
	WriteDB() ITaskDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITaskDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITaskDo
	Not(conds ...gen.Condition) ITaskDo
	Or(conds ...gen.Condition) ITaskDo
	Select(conds ...field.Expr) ITaskDo
	Where(conds ...gen.Condition) ITaskDo
	Order(conds ...field.Expr) ITaskDo
	Distinct(cols ...field.Expr) ITaskDo
	Omit(cols ...field.Expr) ITaskDo
	Join(table schema.Tabler, on ...field.Expr) ITaskDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITaskDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITaskDo
	Group(cols ...field.Expr) ITaskDo
	Having(conds ...gen.Condition) ITaskDo
	Limit(limit int) ITaskDo
	Offset(offset int) ITaskDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskDo
	Unscoped() ITaskDo
	Create(values ...*models.Task) error
	CreateInBatches(values []*models.Task, batchSize int) error
	Save(values ...*models.Task) error
	First() (*models.Task, error)
	Take() (*models.Task, error)
	Last() (*models.Task, error)
	Find() ([]*models.Task, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Task, err error)
	FindInBatches(result *[]*models.Task, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Task) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITaskDo
	Assign(attrs ...field.AssignExpr) ITaskDo
	Joins(fields ...field.RelationField) ITaskDo
	Preload(fields ...field.RelationField) ITaskDo
	FirstOrInit() (*models.Task, error)
	FirstOrCreate() (*models.Task, error)
	FindByPage(offset int, limit int) (result []*models.Task, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITaskDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t taskDo) Debug() ITaskDo {
	return t.withDO(t.DO.Debug())
}

func (t taskDo) WithContext(ctx context.Context) ITaskDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taskDo) ReadDB() ITaskDo {
	return t.Clauses(dbresolver.Read)
}

func (t taskDo) WriteDB() ITaskDo {
	return t.Clauses(dbresolver.Write)
}

func (t taskDo) Session(config *gorm.Session) ITaskDo {
	return t.withDO(t.DO.Session(config))
}

func (t taskDo) Clauses(conds ...clause.Expression) ITaskDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taskDo) Returning(value interface{}, columns ...string) ITaskDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taskDo) Not(conds ...gen.Condition) ITaskDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taskDo) Or(conds ...gen.Condition) ITaskDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taskDo) Select(conds ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taskDo) Where(conds ...gen.Condition) ITaskDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taskDo) Order(conds ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taskDo) Distinct(cols ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taskDo) Omit(cols ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taskDo) Join(table schema.Tabler, on ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taskDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITaskDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taskDo) RightJoin(table schema.Tabler, on ...field.Expr) ITaskDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taskDo) Group(cols ...field.Expr) ITaskDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taskDo) Having(conds ...gen.Condition) ITaskDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taskDo) Limit(limit int) ITaskDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taskDo) Offset(offset int) ITaskDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taskDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taskDo) Unscoped() ITaskDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taskDo) Create(values ...*models.Task) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taskDo) CreateInBatches(values []*models.Task, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taskDo) Save(values ...*models.Task) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taskDo) First() (*models.Task, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Task), nil
	}
}

func (t taskDo) Take() (*models.Task, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Task), nil
	}
}

func (t taskDo) Last() (*models.Task, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Task), nil
	}
}

func (t taskDo) Find() ([]*models.Task, error) {
	result, err := t.DO.Find()
	return result.([]*models.Task), err
}

func (t taskDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Task, err error) {
	buf := make([]*models.Task, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taskDo) FindInBatches(result *[]*models.Task, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taskDo) Attrs(attrs ...field.AssignExpr) ITaskDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taskDo) Assign(attrs ...field.AssignExpr) ITaskDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taskDo) Joins(fields ...field.RelationField) ITaskDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taskDo) Preload(fields ...field.RelationField) ITaskDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taskDo) FirstOrInit() (*models.Task, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Task), nil
	}
}

func (t taskDo) FirstOrCreate() (*models.Task, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Task), nil
	}
}

func (t taskDo) FindByPage(offset int, limit int) (result []*models.Task, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taskDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taskDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taskDo) Delete(models ...*models.Task) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taskDo) withDO(do gen.Dao) *taskDo {
	t.DO = *do.(*gen.DO)
	return t
}
