package consts

type Language string

const (
	Amharic    Language = "am"
	Arabic     Language = "ar"
	Assamese   Language = "as"
	Afrikaans  Language = "af"
	Bangla     Language = "bn"
	Chinese    Language = "zh"
	Danish     Language = "da"
	Dutch      Language = "nl"
	English    Language = "en"
	Finnish    Language = "fi"
	French     Language = "fr"
	German     Language = "de"
	Greek      Language = "el"
	Gujarati   Language = "gu"
	Hausa      Language = "ha"
	Hindi      Language = "hi"
	Igbo       Language = "ig"
	Italian    Language = "it"
	Japanese   Language = "ja"
	Kannada    Language = "kn"
	Korean     Language = "ko"
	Malayalam  Language = "ml"
	Marathi    Language = "mr"
	Nepali     Language = "ne"
	Norwegian  Language = "no"
	Odia       Language = "or"
	Oromo      Language = "om"
	Persian    Language = "fa"
	Portuguese Language = "pt"
	Punjabi    Language = "pa"
	Russian    Language = "ru"
	Sanskrit   Language = "sa"
	Sesotho    Language = "st"
	Shona      Language = "sn"
	Sindhi     Language = "sd"
	Somali     Language = "so"
	Spanish    Language = "es"
	Swahili    Language = "sw"
	Swedish    Language = "sv"
	Tamil      Language = "ta"
	Telugu     Language = "te"
	Tsonga     Language = "ts"
	Tswana     Language = "tn"
	Turkish    Language = "tr"
	Urdu       Language = "ur"
	Undefined  Language = "-"
	Venda      Language = "ve"
	Xhosa      Language = "xh"
	Yoruba     Language = "yo"
	Zulu       Language = "zu"
)
