name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Install dependencies
        run: go get .
      # - name: Run tests
      #   run: go test -v -coverprofile=coverage.txt ./repository
      - name: Build The main server
        run: |
          go build -v -ldflags="-X 'nokib/campwiz/consts.Version=backend-${{ github.sha }}' -X 'nokib/campwiz/consts.Release=backend-${{ github.sha }}' -X 'nokib/campwiz/consts.BuildTime=$(date)' -X 'nokib/campwiz/consts.CommitHash=${{ github.sha }}'" -o campwiz .
      - name: Build Read-only server
        run: |
          mkdir -p read-only
          go build -v -tags readonly  -ldflags="-X 'nokib/campwiz/consts.Version=backend-${{ github.sha }}' -X 'nokib/campwiz/consts.Release=backend-${{ github.sha }}' -X 'nokib/campwiz/consts.BuildTime=$(date)' -X 'nokib/campwiz/consts.CommitHash=${{ github.sha }}'" -o read-only/campwiz-read-only . 
          ls read-only
      - name: Build TaskManager
        run: |
          ls
          cd services/round_service/task-manager/
          go build -v -o campwiz-task-manager .
          ls
          cd ../..
      - name: Setup Deployment Environment
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
      - name: Send Build to Server
        run: |
          rsync -Pav --no-perms --omit-dir-times -e "ssh -i id_rsa" campwiz  "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_REMOTE_PATH }}"
      - name: Send Read-Only Build to Server
        run: |
          rsync -Pav --no-perms --omit-dir-times -e "ssh -i id_rsa" read-only/campwiz-read-only  "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_REMOTE_PATH }}/read-only"
      - name: Send TaskManager Build to Server
        run: |
          rsync -Pav --no-perms --omit-dir-times -e "ssh -i id_rsa" campwiz-task-manager  "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_REMOTE_PATH }}"
      - name: Restart Campwiz
        run: |
          ssh -i id_rsa "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "cd ${{ secrets.SSH_REMOTE_PATH }} && pm2 restart ecosystem.config.js && pm2 restart read-only/campwiz-backend-read-only.config.js"
      - name: Delete SSH Key
        run: |
          rm id_rsa
      - name: Upload test code coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
