name: Deploy to Server
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v -o campwiz .
      - name: Test with the Go CLI
        run: go test
